<?php
	/*
		__________              _____.__       .__     
		\______   \__ __  _____/ ____\__| _____|  |__  
		 |    |  _/  |  \/ ___\   __\|  |/  ___/  |  \ 
		 |    |   \  |  / /_/  >  |  |  |\___ \|   Y  \
		 |______  /____/\___  /|__|  |__/____  >___|  /
				\/     /_____/               \/     \/  Init File */
	/* Create needed Tables */ 
	function xfpinit_internal_tables($mysql) {		
		##########################################################################################################################################
		##### Table Creation     #################################################################################################################		
		$mysql->query("CREATE TABLE IF NOT EXISTS ...");
		$mysql->query("CREATE TABLE IF NOT EXISTS ...");
		return true;}

	/* Initialize */
	function xfpi_internal_init() {
		$object = array();
		#####################################################################
		##### TABLES           ##############################################						
		# Generated by Class
		define('_TABLE_USER_',   				_SQL_PREFIX_."user");  
		define('_TABLE_USER_SESSION_',			_SQL_PREFIX_."user_session");
		define('_TABLE_USER_PERM_',				_SQL_PREFIX_."user_perm");
		define('_TABLE_LOG_IPBL_',				_SQL_PREFIX_."ipbl");
		define('_TABLE_LOG_',					_SQL_PREFIX_."log");
		define('_TABLE_LOG_MYSQL_',				_SQL_PREFIX_."log_sql");
		define('_TABLE_VAR_',					_SQL_PREFIX_."const");
		#####################################################################
		##### Create MySQL     ##############################################
		$object["mysql"] = new x_class_mysql(_SQL_HOST_, _SQL_USER_, _SQL_PASS_, _SQL_DB_);
		if ($object["mysql"]->lasterror != false) { $object["mysql"]->displayError(true); } else { $object["mysql"]->loggingSetup(true, _TABLE_LOG_MYSQL_); }
		
		##########################################################################################################################################
		##### Instance Variables     #############################################################################################################		
		define("_XFP_MAIN_SEOVAR_", "x32rnx"); 
		define("_XFP_THEME_", "theme?"); 
		define("_XFP_COOKIES_", _SITE_COOKIE_PREFIX_);
		define("_XFP_META_DESC_PRE_", "");
		define("_XFP_META_DESC_POST_", " META EXT");
		define("_XFP_META_TITLE_PRE_", "");
		define("_XFP_META_TITLE_POST_", " - TITLE");

		##########################################################################################################################################
		##### Create Non Existing Tables    ######################################################################################################
		$val = false; try {
			$val = mysqli_query($this->mysqlcon, 'SELECT 1 FROM `'.XXXXXX.'`');
		} catch (Exception $e){ 
			xfpi_internal_tables($object["mysql"]);
		} if($val === FALSE) {xfpi_internal_tables($object["mysql"]);}							

		#####################################################################
		##### Get Location    ###############################################
		$object["location"] = xfp_navi_location_seo();
		#####################################################################
		##### Create User     ###############################################
		$object["user"] = new x_class_user($object["mysql"]->mysqlcon, _TABLE_USER_, _TABLE_USER_SESSION_, _SITE_COOKIE_PREFIX_);
		$object["user"]->multi_login(false);
		$object["user"]->login_recover_drop(true);
		$object["user"]->login_field_mail();
		$object["user"]->user_unique(false);
		$object["user"]->log_ip(true);
		$object["user"]->log_activation(true);
		$object["user"]->log_session(true);
		$object["user"]->log_recover(true);
		$object["user"]->log_mail_edit(true);
		$object["user"]->wait_activation_hours(24);
		$object["user"]->wait_recover_hours(24);
		$object["user"]->wait_mail_edit_hours(24);
		$object["user"]->hours_activation(24);
		$object["user"]->hours_recover(24);
		$object["user"]->hours_mail_edit(24);
		$object["user"]->sessions_days(7);
		$object["user"]->cookies_use(true);
		$object["user"]->cookies_days(7);
		$object["user"]->init();
		#####################################################################
		##### Create Vars      ##############################################	
		$object["var"] = new x_class_var($object["mysql"]->mysqlcon, _TABLE_VAR_, "descriptor", "value");
		$object["var"]->sections("section", _BTM_SITE_MODE_);
		$object["var"]->initAsConstant();
		#####################################################################
		##### Create CSRF      ##############################################						
		$object["csrf"] = new x_class_csrf(_SITE_COOKIE_PREFIX_, 300);
		#####################################################################
		##### Create IPBL      ##############################################						
		$object["ipbl"] = new x_class_ipbl($object["mysql"]->mysqlcon, _TABLE_LOG_IPBL_, 10000);
		#####################################################################
		##### Create Perm      ##############################################			
		$object["perm"] = new x_class_perm($object["mysql"]->mysqlcon, _TABLE_USER_PERM_);
		#####################################################################
		##### Save Current User Perms   #####################################	
		$object["user"]->perm = $object["perm"]->getPerm($object["user"]->user_id);
		#####################################################################
		##### Create Log      ##############################################
		$object["log"] = new x_class_log($object["mysql"]->mysqlcon, _TABLE_LOG_);
		#####################################################################
		##### Captcha Setup      ############################################	
		define('_CAPTCHA_FONT_',   	 _MAIN_FOLDER_."/_style/font_captcha.ttf");
		define('_CAPTCHA_WIDTH_',    "200"); 
		define('_CAPTCHA_HEIGHT_',   "70");	
		define('_CAPTCHA_SQUARES_',   mt_rand(4, 15));	
		define('_CAPTCHA_ELIPSE_',    mt_rand(4, 15));	
		define('_CAPTCHA_RANDOM_',    mt_rand(1000, 9999));
		#####################################################################
		##### Move Htaccess    ##############################################	
		if(file_exists(_SITE_PATH_."/dot.htaccess")) {
			rename(_SITE_PATH_."/dot.htaccess", _SITE_PATH_."/.htaccess");
		}
		return $object;
	}

	/* Site Elements */ 
	function xfpi_internal_meta($object) { /* Init Needed Meta */ }	
	function xfpi_internal_headline($object) { /* Init Needed Headline */ }	
	function xfpi_internal_nav($object) { /* Init Needed Nav */ }			
	function xfpi_internal_content($object) { /* Init Needed Nav */ }	
?>