site_name: Bugfish Framework
repo_url: https://github.com/bugfishtm/bugfish-framework
repo_name: bugfishtm/bugfish-framework

nav:
    - Introduction: index.md
    - Download: download.md
    - CSS:
        - Library: css/index.md
    - Javascript:
        - Library: javascript/index.md
    - PHP:
        - Library: functions/index.md
        - 2FA: classes/x_class_2fa.md
        - API: classes/x_class_api.md
        - Benchmark: classes/x_class_benchmark.md
        - Comment: classes/x_class_comment.md
        - Crypt: classes/x_class_crypt.md
        - CSRF: classes/x_class_csrf.md
        - Curl: classes/x_class_curl.md
        - Debug: classes/x_class_debug.md
        - Eventbox: classes/x_class_eventbox.md
        - Hitcounter: classes/x_class_hitcounter.md
        - IP Blacklist: classes/x_class_ipbl.md
        - Logging: classes/x_class_log.md
        - Mail: classes/x_class_mail.md
        - Mail Item: classes/x_class_mail_item.md
        - Mail Template: classes/x_class_mail_template.md
        - MySQL: classes/x_class_mysql.md
        - MySQL Item: classes/x_class_mysql_item.md
        - Permission: classes/x_class_perm.md
        - Permission Item: classes/x_class_perm_item.md
        - Redis: classes/x_class_redis.md
        - Referer: classes/x_class_referer.md
        - Session Blocking: classes/x_class_block.md
        - Table: classes/x_class_table.md
        - Translations: classes/x_class_lang.md
        - User: classes/x_class_user.md
        - Variables: classes/x_class_var.md
        - Version: classes/x_class_version.md
        - Zip: classes/x_class_zip.md
    - Support: support.md
    - License: license.md
    - Impressum: https://bugfishtm.blogspot.com/2023/05/impressum.html
    - Privacy: https://bugfishtm.blogspot.com/2023/05/privacy.html
    - More by Bugfish: https://bugfishtm.github.io
 
theme:
  name: material
  logo: ./logo.png
  favicon: ./favicon.ico
  primary: deep orange
  language: 'en'
  accent: deep orange
  font: false
  features:
    - content.code.copy
  palette:
    - scheme: slate
      primary: deep orange
      accent: deep orange

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
    - mkdocstrings
    - search
    - mkdocs-video
    - glightbox
    - meta-descriptions:
       export_csv: false
       quiet: false
       enable_checks: false
       min_length: 50
       max_length: 160
       trim: false
    
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
use_directory_urls: false

extra:
  meta:
    author: "Jan-Maurice Dahlmanns"